"""empty message

Revision ID: 837795ce6c46
Revises: d292d6d297e3
Create Date: 2021-04-24 13:24:03.277950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837795ce6c46'
down_revision = 'd292d6d297e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_showing_by_admin', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_showing_by_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_showing_by_user')
    op.drop_column('products', 'is_showing_by_admin')
    # ### end Alembic commands ###
