"""empty message

Revision ID: 87c8d83fc9b3
Revises: 
Create Date: 2021-04-23 20:52:33.333190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c8d83fc9b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('low_content', sa.String(), nullable=True))
    op.add_column('products', sa.Column('low_title', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_low_title'), 'products', ['low_title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_low_title'), table_name='products')
    op.drop_column('products', 'low_title')
    op.drop_column('products', 'low_content')
    # ### end Alembic commands ###
