"""empty message

Revision ID: d292d6d297e3
Revises: 87c8d83fc9b3
Create Date: 2021-04-24 11:35:04.481012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd292d6d297e3'
down_revision = '87c8d83fc9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
